format_version: v1.0
configName: mchv3_sam_e70_pim
folderName: mchv3_sam_e70_pim
frameworkPath: D:\Release
processor: ATSAME70Q21B
projectName: mchv3_sam_e70_pim
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME70_DFP\4.9.129\same70b\atdf\ATSAME70Q21B.atdf
