format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_E70_PIM_MC_Board, bsp: 'true'}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: BSP_BOARD_SEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: dsPICDEM MCLV-2}
  - type: Float
    attributes: {id: BSP_IA_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '15.0'}
  - type: Float
    attributes: {id: BSP_IA_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '1.65'}
  - type: Integer
    attributes: {id: BSP_IA_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '34'}
  - type: Float
    attributes: {id: BSP_IA_SHUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '0.025'}
  - type: Float
    attributes: {id: BSP_IB_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '15.0'}
  - type: Float
    attributes: {id: BSP_IB_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '1.65'}
  - type: Integer
    attributes: {id: BSP_IB_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '25'}
  - type: Float
    attributes: {id: BSP_IB_SHUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '0.025'}
  - type: Float
    attributes: {id: BSP_IDC_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '15.0'}
  - type: Float
    attributes: {id: BSP_IDC_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '1.65'}
  - type: Integer
    attributes: {id: BSP_IDC_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '22'}
  - type: Float
    attributes: {id: BSP_IDC_SHUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '0.025'}
  - type: Float
    attributes: {id: BSP_VDC_BOTTOM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '2.0'}
  - type: Integer
    attributes: {id: BSP_VDC_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '24'}
  - type: Float
    attributes: {id: BSP_VDC_TOP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '30.0'}
  - type: Integer
    attributes: {id: BSP_VPOT_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '21'}
  - type: Integer
    attributes: {id: MCBSP_ENCODER_QEA_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '102'}
  - type: Integer
    attributes: {id: MCBSP_ENCODER_QEB_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '99'}
  - type: Integer
    attributes: {id: MCBSP_PWMAH_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '64'}
  - type: Integer
    attributes: {id: MCBSP_PWMAL_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '55'}
  - type: Integer
    attributes: {id: MCBSP_PWMBH_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '68'}
  - type: Integer
    attributes: {id: MCBSP_PWMBL_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '52'}
  - type: Integer
    attributes: {id: MCBSP_PWMCH_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '42'}
  - type: Integer
    attributes: {id: MCBSP_PWMCL_PIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '53'}
  - type: Integer
    attributes: {id: MCPMSMFOC_BUTTON0_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '40'}
  - type: Integer
    attributes: {id: MCPMSMFOC_BUTTON1_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '38'}
  - type: Integer
    attributes: {id: MCPMSMFOC_LED0_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '127'}
  - type: Integer
    attributes: {id: MCPMSMFOC_LED1_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '56'}
  - type: Float
    attributes: {id: MCPMSMFOC_VOLTAGE_MAGNITUDE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: BSP_SAM_E70_PIM_MC_Board, value: '24.0'}
- type: ElementPosition
  attributes: {x: '134', y: '500', id: BSP_SAM_E70_PIM_MC_Board}
