format_version: v1.0
type: UniqueComponent
attributes: {id: X2CScope}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: UART0}
  - type: String
    attributes: {id: X2C_COMM_INSTANCE_RECEIVE_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: '9'}
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE_RECEIVE_UART0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: PA9}
  - type: String
    attributes: {id: X2C_COMM_INSTANCE_TRANSMIT_FINAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: '10'}
  - type: Combo
    attributes: {id: X2C_COMM_INSTANCE_TRANSMIT_UART0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: PA10}
  - type: String
    attributes: {id: X2C_SCOPE_PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: UART0}
  - type: String
    attributes: {id: X2C_SCOPE_UART_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: uart0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: x2cScopeUartDependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: uart0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: UART0_UART}
  - type: DirectCapability
    attributes: {id: x2cScope_Scope}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_X2CSCOPE}
- type: ElementPosition
  attributes: {x: '134', y: '349', id: X2CScope}
